relativeURLs = true
uglyURLs = true
title = "Samuel Kilian"
theme = "gohugo-theme-ananke"


SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
[pagination]
  pagerSize = 1

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"

[params.ananke]
  show_recent_posts = false

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
    "instagram",
    "youtube",
    "spotify",
    "facebook"
  ]

[params.mysite]
  impressum = "/impressum"

[params.ananke.social.instagram]
  username = "samuelkilian.de"
  url = "https://www.instagram.com/samuelkilian.de/"

[params.ananke.social.youtube]
  username = "samuel.kilian"
  url = "https://www.youtube.com/@samuel.kilian/"

[params.ananke.social.spotify]
  username = "1Qgjs72RXBJQetKofNaFvL?si=odU0lpzNQ1mkqkV2QP3I7w"
  url = "https://open.spotify.com/intl-de/artist/1Qgjs72RXBJQetKofNaFvL?si=odU0lpzNQ1mkqkV2QP3I7w"

[params.ananke.social.facebook]
  name = "SamuelKilianHD"
  url = "https://www.facebook.com/SamuelKilianHD"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  

