relativeURLs = true
uglyURLs = true
title = "Samuel Kilian"
theme = "gohugo-theme-ananke"


SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"

[params.mysite]
  impressum = "/impressum"

[[params.ananke_socials]]
  name = "instagram2"
  url = "https://www.instagram.com/samuel.klang/"

[[params.ananke_socials]]
  name = "youtube2"
  url = "https://www.youtube.com/@samuel.kilian/"

[[params.ananke_socials]]
  name = "spotify2"
  url = "https://open.spotify.com/intl-de/artist/1Qgjs72RXBJQetKofNaFvL?si=odU0lpzNQ1mkqkV2QP3I7w"

[[params.ananke_socials]]
  name = "facebook2"
  url = "https://www.facebook.com/SamuelKilianHD"

[[params.ananke_socials]]
  name = "nelevz"
  url = "/nelevz"

  

[menu]
[[menu.main]]
  name = 'Termine'
  pageRef = '/termine'
  weight = 10
[[menu.main]]
  name = 'Musik'
  pageRef = '/Musik'
  weight = 20
[[menu.main]]
  name = 'Leben & Werk'
  pageRef = '/about'
  weight = 30
[[menu.main]]
  name = 'Kontakt'
  pageRef = '/contact'
  weight = 40
